USE PRZEWOZY_POZAREGIONALNE_DW

DELETE FROM AWARIA_WAGONU;
DELETE FROM AWARIA_LOKOMOTYWY;
DELETE FROM JUNK_AWARII;
DELETE FROM KURS_WAGON;
DELETE FROM KURS;
DELETE FROM WAGON;
DELETE FROM LOKOMOTYWA;
DELETE FROM STACJA;
DELETE FROM MASZYNISTA;
DELETE FROM JUNK;
/* Pytanie co z junk'ami - tak jak czas i data czy za kazdym razem */